FROM eugenmayer/jodconverter:rest

MAINTAINER jiangyuanlin@163.com

RUN apt-get update &&  apt -y install curl
# 字体
RUN cd /usr/share/fonts/ && curl  -O https://raw.githubusercontent.com/qq275860560/jobconverter/master/src/main/centos/usr/share/fonts/SimHei.ttf 
  

 